{% set name = "external-systems" %}
{% set version = "0.106.0" %}
{% set u_name = "external_systems" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ u_name }}-{{ version }}.tar.gz
  sha256: cb7687cb4e1deaed23b233048da424b5032832b5c26d2eef44f31ea02defba88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - frozendict >=2.4.6
    - requests >=2.32.3

test:
  imports:
    - external_systems
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/palantir/external-systems
  summary: A Python library for interacting with Foundry Sources
  license: Apache-2.0
  license_family: Apache
  # https://github.com/palantir/external-systems/blob/develop/LICENSE.txt
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - uz1pk
    - jettdc
    - jacobbohac
    - afloren-palantir
